CREATE DATABASE IF NOT EXISTS nec_form_app_db;

USE nec_form_app_db;

CREATE TABLE IF NOT EXISTS teams (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS forms (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  long_id TEXT NOT NULL,
  t_id INT NOT NULL,
  hypothesis TEXT NOT NULL,
  observation TEXT NOT NULL,
  observation_result TEXT NOT NULL,
  hearing TEXT NOT NULL,
  hearing_result TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS form_groupings (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS form_settings (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  t_id INT NOT NULL,
  form_id TEXT NOT NULL,
  form_grouping_id INT NOT NULL,
  color TEXT NOT NULL,
  background_color TEXT NOT NULL,
  position_top FLOAT NOT NULL,
  position_left FLOAT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teams_colors (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  t_id INT NOT NULL,
  color TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS all_view_settings (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  long_id TEXT NOT NULL,
  title TEXT NOT NULL,
  t_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS all_view_form_cards (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  t_id INT NOT NULL,
  form_id TEXT NOT NULL,
  view_id TEXT NOT NULL,
  form_grouping_id INT NOT NULL,
  color TEXT NOT NULL,
  background_color TEXT NOT NULL,
  position_top FLOAT NOT NULL,
  position_left FLOAT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);