CREATE DATABASE IF NOT EXISTS nec_form_app_db;

USE nec_form_app_db;

CREATE TABLE IF NOT EXISTS teams (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS forms (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  long_id TEXT NOT NULL,
  t_id INT NOT NULL,
  hypothesis TEXT NOT NULL,
  observation TEXT NOT NULL,
  observation_result TEXT NOT NULL,
  hearing TEXT NOT NULL,
  hearing_result TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);